USE comp3161_db;

DROP TEMPORARY TABLE IF EXISTS digits;
CREATE TEMPORARY TABLE digits (
    d TINYINT PRIMARY KEY
);

INSERT INTO digits (d) VALUES
    (0), (1), (2), (3), (4), (5), (6), (7), (8), (9);

INSERT INTO users (user_code, full_name, email, password_hash, role_id)
VALUES
    ('admin001', 'Admin User 1', 'admin001@school.edu', 'admin123', 1),
    ('admin002', 'Admin User 2', 'admin002@school.edu', 'admin123', 1),
    ('admin003', 'Admin User 3', 'admin003@school.edu', 'admin123', 1),
    ('admin004', 'Admin User 4', 'admin004@school.edu', 'admin123', 1),
    ('admin005', 'Admin User 5', 'admin005@school.edu', 'admin123', 1);

INSERT INTO users (user_code, full_name, email, password_hash, role_id)
SELECT
    CONCAT('lect', LPAD(seq_num, 3, '0')),
    CONCAT('Lecturer ', seq_num),
    CONCAT('lect', LPAD(seq_num, 3, '0'), '@school.edu'),
    'lecturer123',
    2
FROM (
    SELECT
        ROW_NUMBER() OVER (ORDER BY a.d, b.d) AS seq_num
    FROM digits a
    CROSS JOIN digits b
    LIMIT 40
) numbered_lecturers;

INSERT INTO users (user_code, full_name, email, password_hash, role_id)
SELECT
    CONCAT('stud', LPAD(seq_num, 6, '0')),
    CONCAT('Student ', seq_num),
    CONCAT('stud', LPAD(seq_num, 6, '0'), '@school.edu'),
    'student123',
    3
FROM (
    SELECT
        ROW_NUMBER() OVER (ORDER BY a.d, b.d, c.d, d.d, e.d) AS seq_num
    FROM digits a
    CROSS JOIN digits b
    CROSS JOIN digits c
    CROSS JOIN digits d
    CROSS JOIN digits e
    LIMIT 100000
) numbered_students;

INSERT INTO courses (course_code, course_name, description, created_by)
SELECT
    CONCAT('COMP', LPAD(seq_num, 4, '0')),
    CONCAT('Course ', seq_num),
    CONCAT('Autogenerated course description for course ', seq_num),
    1
FROM (
    SELECT
        ROW_NUMBER() OVER (ORDER BY a.d, b.d, c.d) AS seq_num
    FROM digits a
    CROSS JOIN digits b
    CROSS JOIN digits c
    LIMIT 200
) numbered_courses;

INSERT INTO course_lecturers (course_id, lecturer_id)
SELECT
    c.course_id,
    lecturer_user.user_id
FROM (
    SELECT
        course_id,
        ROW_NUMBER() OVER (ORDER BY course_id) AS course_position
    FROM courses
) c
JOIN (
    SELECT
        user_id,
        ROW_NUMBER() OVER (ORDER BY user_id) AS lecturer_position
    FROM users
    WHERE role_id = 2
) lecturer_user
    ON lecturer_user.lecturer_position = FLOOR((c.course_position - 1) / 5) + 1;

INSERT IGNORE INTO course_enrollments (course_id, student_id)
SELECT
    ((student_position - 1) MOD 200) + 1 AS course_id,
    user_id
FROM (
    SELECT
        user_id,
        ROW_NUMBER() OVER (ORDER BY user_id) AS student_position
    FROM users
    WHERE role_id = 3
) s;

INSERT IGNORE INTO course_enrollments (course_id, student_id)
SELECT
    ((student_position + 66 - 1) MOD 200) + 1 AS course_id,
    user_id
FROM (
    SELECT
        user_id,
        ROW_NUMBER() OVER (ORDER BY user_id) AS student_position
    FROM users
    WHERE role_id = 3
) s;

INSERT IGNORE INTO course_enrollments (course_id, student_id)
SELECT
    ((student_position + 132 - 1) MOD 200) + 1 AS course_id,
    user_id
FROM (
    SELECT
        user_id,
        ROW_NUMBER() OVER (ORDER BY user_id) AS student_position
    FROM users
    WHERE role_id = 3
) s;

INSERT IGNORE INTO course_enrollments (course_id, student_id)
SELECT
    ((student_position + 17 - 1) MOD 200) + 1 AS course_id,
    user_id
FROM (
    SELECT
        user_id,
        ROW_NUMBER() OVER (ORDER BY user_id) AS student_position
    FROM users
    WHERE role_id = 3
) s
WHERE MOD(student_position, 2) = 0;

INSERT INTO calendar_events (course_id, title, description, start_datetime, end_datetime, created_by)
SELECT
    course_id,
    CONCAT('Orientation for Course ', course_id),
    'Initial orientation event',
    TIMESTAMP('2026-05-01 09:00:00') + INTERVAL (course_id - 1) DAY,
    TIMESTAMP('2026-05-01 11:00:00') + INTERVAL (course_id - 1) DAY,
    1
FROM courses;

INSERT INTO forums (course_id, title, description, created_by)
SELECT
    course_id,
    CONCAT('General Discussion - ', course_code),
    'Primary forum for course discussion',
    1
FROM courses;

INSERT INTO discussion_threads (forum_id, title, created_by)
SELECT
    forum_id,
    'Welcome Thread',
    created_by
FROM forums;

INSERT INTO thread_posts (thread_id, parent_post_id, user_id, body)
SELECT
    thread_id,
    NULL,
    created_by,
    'Welcome to the course forum. Use this thread for introductions.'
FROM discussion_threads;

INSERT INTO content_sections (course_id, title, position_no)
SELECT course_id, 'Week 1', 1 FROM courses
UNION ALL
SELECT course_id, 'Week 2', 2 FROM courses;

INSERT INTO course_contents (course_id, section_id, title, content_type, resource_url, file_reference, description, uploaded_by)
SELECT
    cs.course_id,
    cs.section_id,
    CONCAT(cs.title, ' Overview'),
    'slide',
    CONCAT('https://school.edu/content/course-', cs.course_id, '/section-', cs.section_id),
    NULL,
    'Autogenerated lecture slides',
    cl.lecturer_id
FROM content_sections cs
JOIN course_lecturers cl ON cl.course_id = cs.course_id;

INSERT INTO assignments (course_id, title, description, due_datetime, max_score, created_by)
SELECT
    c.course_id,
    CONCAT('Assignment 1 - ', c.course_code),
    'Autogenerated assignment for testing',
    TIMESTAMP('2026-06-01 23:59:00') + INTERVAL (c.course_id - 1) DAY,
    100,
    cl.lecturer_id
FROM courses c
JOIN course_lecturers cl ON cl.course_id = c.course_id;

INSERT INTO assignment_submissions (assignment_id, student_id, submission_text, submission_url)
SELECT
    a.assignment_id,
    ce.student_id,
    CONCAT('Submission by student ', ce.student_id, ' for assignment ', a.assignment_id),
    CONCAT('https://school.edu/submissions/', a.assignment_id, '/', ce.student_id)
FROM assignments a
JOIN course_enrollments ce ON ce.course_id = a.course_id
WHERE ce.student_id IN (
    SELECT user_id
    FROM users
    WHERE role_id = 3
      AND user_id <= (
          SELECT MIN(user_id) + 9999
          FROM users
          WHERE role_id = 3
      )
);

INSERT INTO assignment_grades (submission_id, graded_by, score, feedback)
SELECT
    s.submission_id,
    cl.lecturer_id,
    60 + MOD(s.submission_id, 41),
    'Autogenerated feedback'
FROM assignment_submissions s
JOIN assignments a ON a.assignment_id = s.assignment_id
JOIN course_lecturers cl ON cl.course_id = a.course_id;
